name: Heimdall Vuetify Workflow
on:
  push:
  pull_request:
    
jobs:
  test:
    name: Test on the latest MacOS 
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: npm install
        run: |
          npm install
      - name: npm build
        run: |
          npm run build
      - name: npm test
        run: | 
          npm run test
      - name: npm lint
        run: |
          npm run lint
      - name: npm unit test
        run: |
          npm run test:unit
        env:
          CI: true
        
        
