name: Heimdall Vuetify Workflow
on:
  push:
  pull_request:
    
jobs:
  test:
    name: Test on the latest MacOS 
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: npm install, build, and test
        run: |
          npm install
          npm run serve
          npm run build 
          npm run test
          npm run lint
          npm run test:unit
        env:
          CI: true
        
        
