name: heimdall-vuetify
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, windows-2019, windows-2016, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-latest, macOS-10.14]
        #node: [4, 6, 8, 10]
    steps:
      - name: Checkout heimdall-vuetify
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
      - name: Install npm
        run: |
          npm install
      - name: Build with npm
        run: |
          npm run build
      - name: Test with npm
        run: | 
          npm run test
      - name: Lint with npm 
        run: |
          npm run lint
      - name: Run unit tests with npm 
        run: |
          npm run test:unit
        env:
          CI: true
        
        
